services:
    web:
        image: app-name:latest
        build:
            target: web
            context: .
        env_file:
            - .env
        ports:
            - "86:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        platform: "linux/arm64"
        image: mysql:latest
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3305:3305"
        volumes:
            - dbdata:/var/lib/mysql

    phpmyadmin:
        image: "phpmyadmin:latest"
        ports:
            - "84:80"

volumes:
    dbdata: